In [1]:
import pandas as pd

# ÖDEV1 
 Maximum kredi limiti nedir? Hangi müşteriye ait?

In [ ]:
 select customerName, customerNumber,
   max(creditLimit) as kredi_limiti
   from customers;

In [2]:
cevap1= pd.read_csv("sqlödev2_1.csv")
cevap1

        customerName  customerNumber  kredi_limiti
0  Atelier graphique             103      227600.0

# ÖDEV2
Her ülkeden kaç müşteri var?

In [ ]:
SELECT
country,
count(*) as Müşteri_Sayısı
FROM customers
GROUP BY country

In [3]:
cevap1= pd.read_csv("sqlödev2_2.csv")
cevap1

         country  Müşteri_Sayısı
0         France              12
1            USA              36
2      Australia               5
3         Norway               3
4         Poland               1
5        Germany              13
6          Spain               7
7         Sweden               2
8        Denmark               2
9      Singapore               3
10      Portugal               2
11         Japan               2
12       Finland               3
13            UK               5
14       Ireland               2
15        Canada               3
16     Hong Kong               1
17         Italy               4
18   Switzerland               3
19   Netherlands               1
20       Belgium               2
21   New Zealand               4
22  South Africa               1
23       Austria               2
24   Philippines               1
25        Russia               1
26        Israel               1

# ÖDEV3
En az sipariş veren müşteri numarası ve sipariş sayısı nedir (orders tablosundan)?

In [ ]:
SELECT customerNumber, min(siparis_sayisi)
FROM(SELECT customerNumber,count(*) as siparis_sayisi
FROM orders
GROUP BY customerNumber
order by siparis_sayisi asc) as siparis;

In [4]:
cevap1= pd.read_csv("sqlödev2_3.csv")
cevap1

   customerNumber  min(siparis_sayisi)
0             415                    1